<a href="https://colab.research.google.com/github/Yashchaure2006/Data_Science_Lab/blob/main/exp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Determinant of matrix without Numpy

print("Enter the elements of the 3x3 matrix row-wise:")

matrix = []
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

determinant = (
    a * (e*i - f*h)
    - b * (d*i - g*f)
    + c * (d*h - e*g)
)

print("\nDeterminant of the matrix:")
print(determinant)


Enter the elements of the 3x3 matrix row-wise:
Enter row 1: 1 2 3 
Enter row 2: 2 4 5 
Enter row 3: 5 6 7 

Determinant of the matrix:
-4


In [4]:
#Detminant of matrix using Numpy

import numpy as np

print("Enter the elements of 3x3 matrix row-wise:")

elements = []
for i in range(3):
    row = list(map(int, input(f"Enter the row {i+1}(elements seperated by space):").split()))
    elements.append(row)

matrix = np.array(elements)

deteminant = np.linalg.det(matrix)

print("\nmatrix: ")
print(matrix)

print("determinant of the given matrix is: ")
print(deteminant)

Enter the elements of 3x3 matrix row-wise:
Enter the row 1(elements seperated by space):1 2 3 
Enter the row 2(elements seperated by space):4 5 6 
Enter the row 3(elements seperated by space): 5 6 7

matrix: 
[[1 2 3]
 [4 5 6]
 [5 6 7]]
determinant of the given matrix is: 
3.552713678800486e-15


In [7]:

#Inverse of the matrix without using Numpy

print("Enter the elements of the 3x3 matrix row wise:")

matrix = []
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

det = (
    a * (e*i - f*h)
    - b * (d*i - g*f)
    + c * (d*h - e*g)
)

print("\nDeterminant of the matrix:")
print(det)

if det == 0:
    print("Inverse of this matrix does not exist")
else:
    inverse = [

            [(e*i - f*h)/det, (c*h - b*i)/det, (b*f - c*e)/det],
            [(f*g - d*i)/det, (a*i - c*g)/det, (c*d - a*f)/det],
            [(d*h - e*g)/det, (b*g - a*h)/det, (a*e - b*d)/det]

    ]

print("\nInverse of the matrix is: ")
for row in inverse:
    print(row)

Enter the elements of the 3x3 matrix row wise:
Enter row 1: 1 2 3 
Enter row 2: 7 5  6
Enter row 3: 1 4 8 

Determinant of the matrix:
-15

Inverse of the matrix is: 
[-1.0666666666666667, 0.26666666666666666, 0.2]
[3.3333333333333335, -0.3333333333333333, -1.0]
[-1.5333333333333334, 0.13333333333333333, 0.6]


In [8]:




#inverse of matrix using Numpy

# Finding inverse of the matrix using function

import numpy as np

print("Enter elements of 3x3 matrix:")

A = []

for i in range(3):
    row = []
    for j in range(3):
        value = float(input(f"a[{i+1}][{j+1}]: "))
        row.append(value)
    A.append(row)

A = np.array(A)

print("\nInverse of the matrix:")
print(np.linalg.inv(A))





Enter elements of 3x3 matrix:
a[1][1]: 1 
a[1][2]: 3 
a[1][3]: 5
a[2][1]: 7
a[2][2]: 4
a[2][3]: 2
a[3][1]: 7
a[3][2]: 8
a[3][3]: 9

Inverse of the matrix:
[[ 1.53846154  1.         -1.07692308]
 [-3.76923077 -2.          2.53846154]
 [ 2.15384615  1.         -1.30769231]]


In [11]:
#Solving system of Linear equation without using Numpy

print("Solve a system of 2 equations of the form:")
print("a1*x + b1*y = c1")
print("a2*x + b2*y = c2")

a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

detA = a1*b2 - a2*b1

if detA == 0:
    print("The system has no unique solution (determinant is zero).")
else:
    det_x = c1*b2 - c2*b1
    det_y = a1*c2 - a2*c1

    x = det_x / detA
    y = det_y / detA

    print("\nSolution of the system:")
    print(f"x = {round(x, 2)} , y = {round(y, 2)}")


Solve a system of 2 equations of the form:
a1*x + b1*y = c1
a2*x + b2*y = c2
Enter a1: 2 
Enter b1: 7
Enter c1: 5
Enter a2: 6
Enter b2: 8
Enter c2: 1

Solution of the system:
x = -1.27 , y = 1.08


In [10]:
# Solve system of 2 linear equations using NumPy

import numpy as np

print("Solve the system:")
print("a1*x + b1*y = c1")
print("a2*x + b2*y = c2")

# Input values
a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

# Create coefficient matrix A
A = np.array([[a1, b1],
              [a2, b2]])

# Create constant matrix B
B = np.array([c1, c2])

# Check determinant
det = np.linalg.det(A)

if det == 0:
    print("\nThe system has no unique solution (Determinant is zero).")
else:
    solution = np.linalg.solve(A, B)

    print("\nSolution of the system:")
    print("x =", solution[0])
    print("y =", solution[1])


Solve the system:
a1*x + b1*y = c1
a2*x + b2*y = c2
Enter a1: 1 
Enter b1: 2
Enter c1: 8
Enter a2: 5
Enter b2: 3
Enter c2: 4

Solution of the system:
x = -2.285714285714286
y = 5.142857142857143
